source "https://rubygems.org"

ruby "2.7.0"
gem "sinatra"
gem "sinatra-contrib"
gem "erubis"

gem "pry"
gem 'minitest'
gem 'rack-test'
gem 'redcarpet'
gem 'bcrypt'

group :production do
  gem "puma"
end
